[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 600 --worker-class gthread --threads 4"
